@host = http://localhost:3000/api/auth

### 회원가입
POST {{host}}/signup
Content-Type: application/json

{
   "email": "example6@example.com",
   "password": "eXampLeP@ss",
   "passwordConfirm": "eXampLeP@ss",
   "name": "관리자6"
}

### 로그인
POST {{host}}/signin
Content-Type: application/json

{
   "email": "example6@example.com",
   "password": "eXampLeP@ss"
}