@host = http://localhost:3000/api/users
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTcwMjI3NDAzNywiZXhwIjoxNzAyMzE3MjM3fQ.td_hnvhQewNadEinYOjATIzIfjbYRcKL3zfHWlWTT_E
### 내 정보 조회
GET {{host}}/me
Authorization: Bearer {{accessToken}}


